/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import java.io.File;
import java.util.List;

import javax.xml.parsers.SAXParser;
import javax.xml.parsers.SAXParserFactory;

import lombok.extern.slf4j.Slf4j;

@Slf4j
public class App {
    public static void main(String[] args) {
        File file = new File("data/data.xml");
		SAXParserFactory factory = SAXParserFactory.newInstance();
		
		try {
			SAXParser parser = factory.newSAXParser();
			ItemSaxHandler handler = new ItemSaxHandler();
			parser.parse(file, handler);
			
			List<ItemVo> list = handler.getItems();

            int totalCount = handler.getTotalCount();
            String resultCode = handler.getResultCode();
            log.debug("=============== total count : {} ======================", totalCount);
            log.debug("=============== result code : {} ======================", resultCode);

            list.forEach(item -> log.debug(item.toString()));
			
            log.debug("list size : {}", list.size());
		}catch(Exception e) {
			e.printStackTrace();
		}	
    }
}
